/*@ begin PerfTuning (
 def build {
  arg build_command = 'gcc -O0';
 }
 def performance_counter {
  arg method = 'basic timer';
  arg repetitions = 10;
 }
 def performance_params {
  param UF[] = range(1,33);
 }

 def input_params {
  param N[] = [10000000];
 }

 def input_vars {
  decl static double y[N] = 0;
  decl double a1 = random;
  decl double a2 = random;
  decl double a3 = random;
  decl static double x1[N] = random;
  decl static double x2[N] = random;
  decl static double x3[N] = random;
 }
 def search {
 arg algorithm = 'Simplex';
 arg time_limit = 10;
 arg total_runs = 10;
 arg simplex_local_distance = 2;
 arg simplex_reflection_coef = 1.5;
 arg simplex_expansion_coef = 2.5;
 arg simplex_contraction_coef = 0.6;
 arg simplex_shrinkage_coef = 0.7;
 }

) @*/
/**-- (Generated by Orio) 
Best performance cost: 
  [0.0374478, 0.0383966, 0.0439375, 0.0447629, 0.0423421, 0.0396897, 0.0392676, 0.0382546, 0.0381784, 0.0380815] 
Tuned for specific problem sizes: 
  N = 10000000 
Best performance parameters: 
  UF = 5 
--**/


int i;

/*@ begin Loop (
    transform Unroll(ufactor=UF)
    for (i=0; i<=N-1; i++)
	{
	   y[i] = y[i] + a1*x1[i] + a2*x2[i] + a3*x3[i];
    }
) @*/
{
  int i;
  for (i=0; i<=N-5; i=i+5) {
    y[i]=y[i]+a1*x1[i]+a2*x2[i]+a3*x3[i];
    y[(i+1)]=y[(i+1)]+a1*x1[(i+1)]+a2*x2[(i+1)]+a3*x3[(i+1)];
    y[(i+2)]=y[(i+2)]+a1*x1[(i+2)]+a2*x2[(i+2)]+a3*x3[(i+2)];
    y[(i+3)]=y[(i+3)]+a1*x1[(i+3)]+a2*x2[(i+3)]+a3*x3[(i+3)];
    y[(i+4)]=y[(i+4)]+a1*x1[(i+4)]+a2*x2[(i+4)]+a3*x3[(i+4)];
  }
  for (i=N-((N-(0))%5); i<=N-1; i=i+1) 
    y[i]=y[i]+a1*x1[i]+a2*x2[i]+a3*x3[i];
}
/*@ end @*/

/*@ end @*/
